version: "2"

services:
  nginx:
    build: ./deploy/nginx/
    ports:
      - 127.0.0.1:8080:80
    links:
      - php
    volumes_from:
      - app
    networks:
      - appnet

  php:
    build: ./deploy/php/
    expose:
      - 9000
    links:
      - mysql
    volumes_from:
      - app
    networks:
      - appnet

  app:
    image: php:7.0-fpm
    volumes:
      - ./src/:/var/www/html
    networks:
      - appnet
    command: "true"

  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    networks:
      - appnet



networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
